hombre(gilberto).
hombre(ancelmo).
hombre(honorato).
hombre(manuel).
hombre(leoncio).
hombre(eugenio).
hombre(maximo).
hombre(vismar).
hombre(jheison).
hombre(francisco).
hombre(rene).
hombre(santiago).
hombre(froilan).
hombre(enrique).
hombre(gualberto).
hombre(samuel).
hombre(daniel).
mujer(susana).
mujer(felicia).
mujer(teresa).
mujer(emiliana).
mujer(nicolasa).
mujer(josefina).
mujer(hilaria).
mujer(seve).
mujer(jhessica).
mujer(bianca).
mujer(lizeth).
mujer(salome).
mujer(agustina).
mujer(juana).
mujer(maxima).
mujer(vasilia).
mujer(rita).
mujer(nicolasaa).
mujer(isidora).
mujer(noemi).
progenitorde(ancelmo,eugenio).
progenitorde(ancelmo,honorato).
progenitorde(ancelmo,manuel).
progenitorde(ancelmo,leoncio).
progenitorde(ancelmo,emiliana).
progenitorde(felicia,eugenio).
progenitorde(felicia,honorato).
progenitorde(felicia,manuel).
progenitorde(felicia,leoncio).
progenitorde(felicia,emiliana).
progenitorde(munuel,agustina).
progenitorde(manuel,juana).
progenitorde(nicolasaa,agustina).
progenitorde(nicolasaa,juana).
progenitorde(honorato,francisco).
progenitorde(honorato,salome).
progenitorde(leoncio,maxima).
progenitorde(leoncio,vasilia).
progenitorde(casiana,maxima).
progenitorde(casiana,vasilia).
progenitorde(eugenio,maximo).
progenitorde(eugenio,hilaria).
progenitorde(eugenio,seve).
progenitorde(eugenio,josefina).
progenitorde(gilberto,nicolasa).
progenitorde(susana,nicolasa).
progenitorde(nicolasa,maximo).
progenitorde(nicolasa,hilaria).
progenitorde(nicolasa,seve).
progenitorde(nicolasa,josefina).
progenitorde(maximo,bianca).
progenitorde(hilaria,jhessica).
progenitorde(hilaria,vismar).
progenitorde(seve,lizeth).
progenitorde(seve,jheison).
progenitorde(emiliana,rene).
progenitorde(emiliana,rita).
parejade(gilberto,susana).
parejade(susana,gilberto).
parejade(ancelmo,felicia).
parejade(felicia,ancelmo).
parejade(eugenio,nicolasa).
parejade(nicolasa,eugenio).
parejade(manuel,nicolasaa).
parejade(nicolasaa,manuel).
parejade(leoncio,casiana).
parejade(casiana,leoncio).
parejade(francisco,isidora).
parejade(isidora,francisco).
parejade(hilaria,santiago).
parejade(santiago,hilaria).
parejade(maximo,noemi).
parejade(noemi,maximo).
parejade(seve,froilan).
parejade(froilan,seve).
parejade(salome,enrique).
parejade(enrique,salome).
parejade(maxima,gualberto).
parejade(gualberto,maxima).
parejade(juana,samuel).
parejade(samuel,juana).
parejade(vacilia,daniel).
parejade(daniel,vacilia).
hijode(X,Y):-progenitorde(Y,X),hombre(X).
hijade(X,Y):-progenitorde(Y,X),mujer(X).
padrede(X,Y):-hombre(X),progenitorde(X,Y).
madrede(X,Y):-mujer(X),progenitorde(X,Y).
hermanosde(X,Y):-progenitorde(Z,X),progenitorde(Z,Y), not(X==Y).
hermanode(X,Y):-hombre(X),hermanosde(X,Y).
hermanade(X,Y):-mujer(X),hermanosde(X,Y).
suegrode(X,Y):-padrede(X,Z),parejade(Y,Z).
suegrade(X,Y):-madrede(X,Z),parejade(Y,Z).
yernode(X,Y):-suegrode(Y,X);suegrade(Y,X),hombre(X).
nuerade(X,Y):-suegrode(Y,X);suegrade(Y,X),mujer(X).
cuñadosde(X,Y):-((parejade(X,Z),hermanosde(Z,Y));(parejade(Y,Z),hermanosde(Z,X))).
cuñadode(X,Y):-cuñadosde(X,Y),hombre(X).
cuñadade(X,Y):-cuñadosde(X,Y),mujer(X).
abuelode(X,Y):-progenitorde(Z,Y),padrede(X,Z).
abuelade(X,Y):-progenitorde(Z,Y),madrede(X,Z).
nietode(X,Y):-progenitorde(Y,Z),progenitorde(Z,X),hombre(X).
nietade(X,Y):-progenitorde(Y,Z),progenitorde(Z,X),mujer(X).
tiode(X,Y):-progenitorde(Z,Y),(hermanode(X,Z);cuñadode(X,Z)).
tiade(X,Y):-progenitorde(Z,Y),(hermanade(X,Z);cuñadade(X,Z)).
primode(X,Y):-progenitorde(Z,X),progenitorde(W,Y),hermanosde(Z,W),hombre(X).
primade(X,Y):-progenitorde(Z,X),progenitorde(W,Y),hermanosde(Z,W),mujer(X).





